

export const getMockOrders = () => ([{
    "id": 1,
    "created_at": "2022-06-28T21:45:58.098-04:00",
    "created_by": "service-account-astur_internal",
    "updated_at": "2022-06-28T21:45:58.098-04:00",
    "updated_by": "service-account-astur_internal",
    "fields": {},
    "order_number": "2",
    "status": "pending",
    "purchase_order": "47210",
    "external_order_id": "123321-123123",
    "sales_channel_id": 1,
    "sales_channel_name": null,
    "sales_channel_type": null,
    "sales_channel_sub_type": null,
    "sales_channel_country": null,
    "send_email": false,
    "create_routings": true,
    "shipping_information": {
        "first_name": "Chan",
        "last_name": "Surname",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "FL",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "billing_information": {
        "first_name": "Chan",
        "last_name": "Surname",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "FL",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "item_tax": 5,
    "ship_tax": 5,
    "shipping": 5,
    "total_item_discount": 12,
    "total_shipping_discount": 2.5,
    "subtotal": 37,
    "total": 42,
    "order_item": [
        {
            "id": 1,
            "created_at": "2022-06-28T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-28T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": "1",
            "order_id": 1,
            "product_id": 3,
            "order_item_status": null,
            "sku": "efgh5678",
            "unit_price": 10.25,
            "quantity": 6,
            "shipped": 6,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": true,
            "giftwrap_price": 0,
            "giftwrap_tax_price": null,
            "gift_message": "hi nick",
            "gift_message_price": 0,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": 5.99,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "total_price": 48.93,
            "other_fees": 0,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "shipping",
                    "price": 5.99
                },
                {
                    "id": 2,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "items",
                    "price": 1.2
                }
            ],
            "customization": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.118-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.118-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "type": "engraving",
                    "message": "foo",
                    "price": 5.99,
                    "tax_price": null
                }
            ],
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": "",
            "external_warehouse_id": "",
            "two_day_shipping": false
        },
        {
            "id": 2,
            "created_at": "2022-06-28T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-28T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": "2",
            "order_id": 1,
            "product_id": 2,
            "order_item_status": null,
            "sku": "abcd1234",
            "unit_price": 10.25,
            "quantity": 5,
            "shipped": 4,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": true,
            "giftwrap_price": 0,
            "giftwrap_tax_price": null,
            "gift_message": "hi nick",
            "gift_message_price": 0,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": 5.99,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "total_price": 48.93,
            "other_fees": 0,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": null,
            "customization": null,
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": null,
            "external_warehouse_id": null,
            "two_day_shipping": false
        },
        {
            "id": 3,
            "created_at": "2022-07-05T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-28T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": null,
            "order_id": 1,
            "product_id": 2,
            "order_item_status": null,
            "sku": "abcd1234",
            "unit_price": 10.25,
            "quantity": 50,
            "shipped": 0,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": null,
            "giftwrap_price": null,
            "giftwrap_tax_price": null,
            "gift_message": null,
            "gift_message_price": null,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": null,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "other_fees": null,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": null,
            "customization": null,
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": null,
            "external_warehouse_id": null,
            "two_day_shipping": false
        },
        {
            "id": 4,
            "created_at": "2022-06-28T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-28T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": null,
            "order_id": 1,
            "product_id": 0,
            "order_item_status": null,
            "sku": "idontexist",
            "unit_price": 10.25,
            "quantity": 2,
            "shipped": 0,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": null,
            "giftwrap_price": null,
            "giftwrap_tax_price": null,
            "gift_message": null,
            "gift_message_price": null,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": null,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "other_fees": null,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": null,
            "customization": null,
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": null,
            "external_warehouse_id": null,
            "two_day_shipping": false
        }
    ],
    "requested_ship_date": "2022-07-03T18:07:30.591Z",
    "requested_delivery_date": "2022-07-03T18:07:30.591Z"
},
{
    "id": 2,
    "created_at": "2022-06-30T21:45:58.098-04:00",
    "created_by": "service-account-astur_internal",
    "updated_at": "2022-06-30T21:45:58.098-04:00",
    "updated_by": "service-account-astur_internal",
    "fields": {},
    "order_number": "3",
    "status": "active",
    "purchase_order": "47242",
    "external_order_id": "123321-123124",
    "sales_channel_id": 3,
    "sales_channel_name": null,
    "sales_channel_type": null,
    "sales_channel_sub_type": null,
    "sales_channel_country": null,
    "send_email": false,
    "create_routings": false,
    "shipping_information": {
        "first_name": "Barney",
        "last_name": "Stinson",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "NY",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "billing_information": {
        "first_name": "Barney",
        "last_name": "Stinson",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "NY",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "item_tax": 5,
    "ship_tax": 5,
    "shipping": 5,
    "total_item_discount": 12,
    "total_shipping_discount": 2.5,
    "subtotal": 25,
    "total": 38,
    "order_item": [
        {
            "id": 1,
            "created_at": "2022-06-30T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-30T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": "1",
            "order_id": 1,
            "product_id": 3,
            "order_item_status": null,
            "sku": "efgh5678",
            "unit_price": 10.25,
            "quantity": 1,
            "shipped": 1,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": true,
            "giftwrap_price": 0,
            "giftwrap_tax_price": null,
            "gift_message": "hi nick",
            "gift_message_price": 0,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": 5.99,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "total_price": 48.93,
            "other_fees": 0,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "shipping",
                    "price": 5.99
                },
                {
                    "id": 2,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "items",
                    "price": 1.2
                }
            ],
            "customization": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.118-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.118-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "type": "engraving",
                    "message": "foo",
                    "price": 5.99,
                    "tax_price": null
                }
            ],
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": "",
            "external_warehouse_id": "",
            "two_day_shipping": false
        },
    ],
    "requested_ship_date": "2022-07-01T18:07:30.591Z",
    "requested_delivery_date": "2022-07-01T18:07:30.591Z"
},
{
    "id": 3,
    "created_at": "2022-07-05T21:45:58.098-04:00",
    "created_by": "service-account-astur_internal",
    "updated_at": "2022-06-30T21:45:58.098-04:00",
    "updated_by": "service-account-astur_internal",
    "fields": {},
    "order_number": "4",
    "status": "active",
    "purchase_order": "47223",
    "external_order_id": "123321-123124",
    "sales_channel_id": 1,
    "sales_channel_name": null,
    "sales_channel_type": null,
    "sales_channel_sub_type": null,
    "sales_channel_country": null,
    "send_email": false,
    "create_routings": true,
    "shipping_information": {
        "first_name": "Jack",
        "last_name": "Goldbear",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "TX",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "billing_information": {
        "first_name": "Giant",
        "last_name": "Dinosaur",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "TX",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "item_tax": 5,
    "ship_tax": 5,
    "shipping": 5,
    "total_item_discount": 12,
    "total_shipping_discount": 2.5,
    "subtotal": 35,
    "total": 56,
    "order_item": [
        {
            "id": 1,
            "created_at": "2022-06-30T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-30T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": "1",
            "order_id": 1,
            "product_id": 3,
            "order_item_status": null,
            "sku": "efgh5678",
            "unit_price": 10.25,
            "quantity": 8,
            "shipped": 6,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": true,
            "giftwrap_price": 0,
            "giftwrap_tax_price": null,
            "gift_message": "hi nick",
            "gift_message_price": 0,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": 5.99,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "total_price": 48.93,
            "other_fees": 0,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "shipping",
                    "price": 5.99
                },
                {
                    "id": 2,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "items",
                    "price": 1.2
                }
            ],
            "customization": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.118-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.118-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "type": "engraving",
                    "message": "foo",
                    "price": 5.99,
                    "tax_price": null
                }
            ],
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": "",
            "external_warehouse_id": "",
            "two_day_shipping": false
        },
    ],
    "requested_ship_date": "2022-07-08T18:07:30.591Z",
    "requested_delivery_date": "2022-07-08T18:07:30.591Z"
},
{
    "id": 4,
    "created_at": "2022-06-30T21:45:58.098-04:00",
    "created_by": "service-account-astur_internal",
    "updated_at": "2022-06-30T21:45:58.098-04:00",
    "updated_by": "service-account-astur_internal",
    "fields": {},
    "order_number": "3",
    "status": "pending",
    "purchase_order": "47219",
    "external_order_id": "123321-123124",
    "sales_channel_id": 1,
    "sales_channel_name": null,
    "sales_channel_type": null,
    "sales_channel_sub_type": null,
    "sales_channel_country": null,
    "send_email": false,
    "create_routings": false,
    "shipping_information": {
        "first_name": "Giant",
        "last_name": "Dinosaur",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "TX",
        "postal_code": "92126",
        "country": "US",
        "email": "Hansg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "billing_information": {
        "first_name": "Hans",
        "last_name": "Mans",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "CA",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "item_tax": 5,
    "ship_tax": 5,
    "shipping": 5,
    "total_item_discount": 12,
    "total_shipping_discount": 2.5,
    "subtotal": 25,
    "total": 38,
    "order_item": [
        {
            "id": 1,
            "created_at": "2022-06-30T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-30T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": "1",
            "order_id": 1,
            "product_id": 3,
            "order_item_status": null,
            "sku": "efgh5678",
            "unit_price": 10.25,
            "quantity": 1,
            "shipped": 0,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": true,
            "giftwrap_price": 0,
            "giftwrap_tax_price": null,
            "gift_message": "hi nick",
            "gift_message_price": 0,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": 5.99,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "total_price": 48.93,
            "other_fees": 0,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "shipping",
                    "price": 5.99
                },
                {
                    "id": 2,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "items",
                    "price": 1.2
                }
            ],
            "customization": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.118-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.118-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "type": "engraving",
                    "message": "foo",
                    "price": 5.99,
                    "tax_price": null
                }
            ],
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": "",
            "external_warehouse_id": "",
            "two_day_shipping": false
        },
    ],
    "requested_ship_date": "2022-07-03T18:07:30.591Z",
    "requested_delivery_date": "2022-07-03T18:07:30.591Z"
},
{
    "id": 5,
    "created_at": "2022-06-30T21:45:58.098-04:00",
    "created_by": "service-account-astur_internal",
    "updated_at": "2022-06-30T21:45:58.098-04:00",
    "updated_by": "service-account-astur_internal",
    "fields": {},
    "order_number": "3",
    "status": "canceled",
    "purchase_order": "47211",
    "external_order_id": "123321-123124",
    "sales_channel_id": 2,
    "sales_channel_name": null,
    "sales_channel_type": null,
    "sales_channel_sub_type": null,
    "sales_channel_country": null,
    "send_email": false,
    "create_routings": true,
    "shipping_information": {
        "first_name": "Ahmet",
        "last_name": "Tok",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "CA",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "billing_information": {
        "first_name": "Ahmet",
        "last_name": "Tok",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "CA",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "item_tax": 5,
    "ship_tax": 5,
    "shipping": 5,
    "total_item_discount": 12,
    "total_shipping_discount": 2.5,
    "subtotal": 25,
    "total": 38,
    "order_item": [
        {
            "id": 1,
            "created_at": "2022-06-30T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-30T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": "1",
            "order_id": 1,
            "product_id": 3,
            "order_item_status": null,
            "sku": "efgh5678",
            "unit_price": 10.25,
            "quantity": 1,
            "shipped": 1,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": true,
            "giftwrap_price": 0,
            "giftwrap_tax_price": null,
            "gift_message": "hi nick",
            "gift_message_price": 0,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": 5.99,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "total_price": 48.93,
            "other_fees": 0,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "shipping",
                    "price": 5.99
                },
                {
                    "id": 2,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "items",
                    "price": 1.2
                }
            ],
            "customization": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.118-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.118-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "type": "engraving",
                    "message": "foo",
                    "price": 5.99,
                    "tax_price": null
                }
            ],
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": "",
            "external_warehouse_id": "",
            "two_day_shipping": false
        },
        {
            "id": 2,
            "created_at": "2022-06-28T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-28T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": "2",
            "order_id": 1,
            "product_id": 2,
            "order_item_status": null,
            "sku": "abcd1234",
            "unit_price": 10.25,
            "quantity": 5,
            "shipped": 5,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": true,
            "giftwrap_price": 0,
            "giftwrap_tax_price": null,
            "gift_message": "hi nick",
            "gift_message_price": 0,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": 5.99,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "total_price": 48.93,
            "other_fees": 0,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": null,
            "customization": null,
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": null,
            "external_warehouse_id": null,
            "two_day_shipping": false
        },
    ],
    "requested_ship_date": "2022-06-28T18:07:30.591Z",
    "requested_delivery_date": "2022-06-28T18:07:30.591Z"
},
{
    "id": 6,
    "created_at": "2022-06-30T21:45:58.098-04:00",
    "created_by": "service-account-astur_internal",
    "updated_at": "2022-06-30T21:45:58.098-04:00",
    "updated_by": "service-account-astur_internal",
    "fields": {},
    "order_number": "3",
    "status": "pending",
    "purchase_order": "47231",
    "external_order_id": "123321-123124",
    "sales_channel_id": 2,
    "sales_channel_name": null,
    "sales_channel_type": null,
    "sales_channel_sub_type": null,
    "sales_channel_country": null,
    "send_email": false,
    "create_routings": true,
    "shipping_information": {
        "first_name": "Jack",
        "last_name": "Morris",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "TX",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "billing_information": {
        "first_name": "Jack",
        "last_name": "Morris",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "TX",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "item_tax": 5,
    "ship_tax": 5,
    "shipping": 5,
    "total_item_discount": 12,
    "total_shipping_discount": 2.5,
    "subtotal": 25,
    "total": 38,
    "order_item": [
        {
            "id": 1,
            "created_at": "2022-06-30T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-30T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": "1",
            "order_id": 1,
            "product_id": 3,
            "order_item_status": null,
            "sku": "efgh5678",
            "unit_price": 10.25,
            "quantity": 5,
            "shipped": 3,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": true,
            "giftwrap_price": 0,
            "giftwrap_tax_price": null,
            "gift_message": "hi nick",
            "gift_message_price": 0,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": 5.99,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "total_price": 48.93,
            "other_fees": 0,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "shipping",
                    "price": 5.99
                },
                {
                    "id": 2,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "items",
                    "price": 1.2
                }
            ],
            "customization": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.118-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.118-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "type": "engraving",
                    "message": "foo",
                    "price": 5.99,
                    "tax_price": null
                }
            ],
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": "",
            "external_warehouse_id": "",
            "two_day_shipping": false
        },
    ],
    "requested_ship_date": "2022-07-28T18:07:30.591Z",
    "requested_delivery_date": "2022-07-28T18:07:30.591Z"
},
{
    "id": 7,
    "created_at": "2022-07-02T21:45:58.098-04:00",
    "created_by": "service-account-astur_internal",
    "updated_at": "2022-06-30T21:45:58.098-04:00",
    "updated_by": "service-account-astur_internal",
    "fields": {},
    "order_number": "5",
    "status": "active",
    "purchase_order": "47215",
    "external_order_id": "123321-123124",
    "sales_channel_id": 3,
    "sales_channel_name": null,
    "sales_channel_type": null,
    "sales_channel_sub_type": null,
    "sales_channel_country": null,
    "send_email": false,
    "create_routings": true,
    "shipping_information": {
        "first_name": "Tony",
        "last_name": "Montana",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "CA",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "billing_information": {
        "first_name": "Tony",
        "last_name": "Montana",
        "company": "acenda",
        "address_1": "8400 Miramar Road",
        "address_2": "Suite 200",
        "city": "San Diego",
        "state": "CA",
        "postal_code": "92126",
        "country": "US",
        "email": "garrettg@acenda.com",
        "phone_number": "9496489019",
        "location": {
            "type": "Point",
            "coordinates": []
        }
    },
    "item_tax": 5,
    "ship_tax": 5,
    "shipping": 5,
    "total_item_discount": 12,
    "total_shipping_discount": 2.5,
    "subtotal": 25,
    "total": 38,
    "order_item": [
        {
            "id": 1,
            "created_at": "2022-06-30T21:45:58.11-04:00",
            "created_by": "service-account-astur_internal",
            "updated_at": "2022-06-30T21:45:58.11-04:00",
            "updated_by": "service-account-astur_internal",
            "fields": {},
            "line_id": "1",
            "order_id": 1,
            "product_id": 3,
            "order_item_status": null,
            "sku": "efgh5678",
            "unit_price": 10.25,
            "quantity": 5,
            "shipped": 5,
            "routed": 0,
            "rerouted": 0,
            "pending": 0,
            "giftwrap": true,
            "giftwrap_price": 0,
            "giftwrap_tax_price": null,
            "gift_message": "hi nick",
            "gift_message_price": 0,
            "gift_message_tax_price": null,
            "total_customization_price": null,
            "total_customization_tax_price": null,
            "total_shipping_price": 5.99,
            "total_shipping_tax_price": null,
            "total_item_tax": null,
            "total_price": 48.93,
            "other_fees": 0,
            "tax_rate": 9.5,
            "total_item_discount": null,
            "total_shipping_discount": null,
            "total_gift_option_price": null,
            "total_gift_option_tax_price": null,
            "discounts": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "shipping",
                    "price": 5.99
                },
                {
                    "id": 2,
                    "created_at": "2022-06-28T21:45:58.116-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.116-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "promotion_code": "red card",
                    "promotion_text": "",
                    "affects": "items",
                    "price": 1.2
                }
            ],
            "customization": [
                {
                    "id": 1,
                    "created_at": "2022-06-28T21:45:58.118-04:00",
                    "created_by": "service-account-astur_internal",
                    "updated_at": "2022-06-28T21:45:58.118-04:00",
                    "updated_by": "service-account-astur_internal",
                    "fields": {},
                    "type": "engraving",
                    "message": "foo",
                    "price": 5.99,
                    "tax_price": null
                }
            ],
            "kit_items": null,
            "expected_shipping_date": null,
            "expected_delivery_date": null,
            "shipping_method": "",
            "external_warehouse_id": "",
            "two_day_shipping": false
        },
    ],
    "requested_ship_date": "2022-07-28T18:07:30.591Z",
    "requested_delivery_date": "2022-07-28T18:07:30.591Z"
}
].sort((a, b) => (a.requested_delivery_date > b.requested_delivery_date ? -1 : 1)))


export const getOneOrder = (id) => {
    return (getMockOrders()).find(a => a.id == id)
}


export const allShipAdvices = () => {
    return ({
        "status": 200,
        "execution_time": 0.0232905,
        "num_results": 2,
        "errors": null,
        "result": [
            {
                "id": 1,
                "created_at": "2022-06-28T21:45:58.137-04:00",
                "created_by": "service-account-astur_internal",
                "updated_at": "2022-06-28T21:45:58.137-04:00",
                "updated_by": "service-account-astur_internal",
                "fields": {},
                "order_id": 1,
                "status": "canceled",
                "notes": "Canceled, missing SKU!",
                "order_routing_status": null,
                "fulfillment_provider_id": 1,
                "warehouse_id": 1,
                "step": 0,
                "sales_channel_id": 1,
                "delivery_information": {
                    "first_name": "Garrett",
                    "last_name": "Griffin",
                    "company": "acenda",
                    "address_1": "8400 Miramar Road",
                    "address_2": "Suite 200",
                    "city": "San Diego",
                    "state": "CA",
                    "postal_code": "92126",
                    "country": "US",
                    "email": "garrettg@acenda.com",
                    "phone_number": "9496489019",
                    "location": {
                        "type": "Point",
                        "coordinates": [
                            32.9161,
                            -117.1402
                        ]
                    }
                },
                "requested_ship_date": "2022-06-08T14:07:30.591-04:00",
                "requested_delivery_date": "2022-06-08T14:07:30.591-04:00",
                "ship_advice_items": [
                    {
                        "id": 1,
                        "created_at": "2022-06-28T21:45:58.148-04:00",
                        "created_by": "service-account-astur_internal",
                        "updated_at": "2022-06-28T21:45:58.148-04:00",
                        "updated_by": "service-account-astur_internal",
                        "fields": {},
                        "ship_advice_id": 1,
                        "order_item_id": 1,
                        "name": "efgh5678",
                        "quantity": 6,
                        "quantity_original": 6,
                        "is_two_day_ship": false
                    }
                ]
            },
            {
                "id": 2,
                "created_at": "2022-06-28T21:45:58.137-04:00",
                "created_by": "service-account-astur_internal",
                "updated_at": "2022-06-28T21:45:58.137-04:00",
                "updated_by": "service-account-astur_internal",
                "fields": {},
                "order_id": 1,
                "step": 3,
                "status": "complete",
                "order_routing_status": null,
                "fulfillment_provider_id": 1,
                "warehouse_id": 2,
                "sales_channel_id": 1,
                "delivery_information": {
                    "first_name": "Garrett",
                    "last_name": "Griffin",
                    "company": "acenda",
                    "address_1": "8400 Miramar Road",
                    "address_2": "Suite 200",
                    "city": "San Diego",
                    "state": "CA",
                    "postal_code": "92126",
                    "country": "US",
                    "email": "garrettg@acenda.com",
                    "phone_number": "9496489019",
                    "location": {
                        "type": "Point",
                        "coordinates": [
                            32.9161,
                            -117.1402
                        ]
                    }
                },
                "requested_ship_date": "2022-06-08T14:07:30.591-04:00",
                "requested_delivery_date": "2022-06-08T14:07:30.591-04:00",
                "ship_advice_items": [
                    {
                        "id": 2,
                        "created_at": "2022-06-28T21:45:58.148-04:00",
                        "created_by": "service-account-astur_internal",
                        "updated_at": "2022-06-28T21:45:58.148-04:00",
                        "updated_by": "service-account-astur_internal",
                        "fields": {},
                        "ship_advice_id": 2,
                        "order_item_id": 2,
                        "name": "abcd1234",
                        "quantity": 5,
                        "quantity_original": 5,
                        "is_two_day_ship": false
                    },
                    {
                        "id": 3,
                        "created_at": "2022-06-28T21:45:58.148-04:00",
                        "created_by": "service-account-astur_internal",
                        "updated_at": "2022-06-28T21:45:58.148-04:00",
                        "updated_by": "service-account-astur_internal",
                        "fields": {},
                        "ship_advice_id": 2,
                        "order_item_id": 3,
                        "name": "abcd1234",
                        "quantity": 8,
                        "quantity_original": 50,
                        "is_two_day_ship": false
                    },
                    {
                        "id": 4,
                        "created_at": "2022-06-28T21:45:58.148-04:00",
                        "created_by": "service-account-astur_internal",
                        "updated_at": "2022-06-28T21:45:58.148-04:00",
                        "updated_by": "service-account-astur_internal",
                        "fields": {},
                        "ship_advice_id": 2,
                        "order_item_id": 3,
                        "name": "abcd1234",
                        "quantity": 42,
                        "quantity_original": 50,
                        "is_two_day_ship": false
                    }
                ]
            },

        ]
    })
}

export const getOneMockWarehouse = () => {
    return ({
        "id": 1,
        "active": true,
        "address": {
            "address_1": "300 Curryer st",
            "city": "Middletown",
            "country": "US",
            "postal_code": "45042",
            "state": "OH"
        },
        "fulfillment_provider_id": 1,
        "inventory_tracking": "basic",
        "name": "my first warehouse",
        "respect_allocations": true,
        "type": "physical",
        "external_id": "123"
    })
}
